Deep decoder
ValerioB88/mind-set pull request #2
Opened 2023-04-04 01:19 UTC by Don-Yin

2023-04-11 10:38 UTC, ValerioB88 requested changes

2023-04-11 10:38 UTC, ValerioB88 commented on src/utils/decoder/README.md
> +            --use_residual_decoder False \
This should be different. It should be so that if the user add the "--use_residual_decoder" then it will use the residual decoder - you shoulnd't also specify "True" after that. I will put the concrete example in the code in the other file.

2023-04-11 10:38 UTC, ValerioB88 commented on src/utils/decoder/train.py
> +parser.add_argument('--use_residual_decoder', metavar='whether to use the deeper residual decoder', default=False)
change it to: parser.add_argument('--use_residual_decoder',  '-resdec' metavar='whether to use the deeper residual decoder', action='store_true')

In this way the user can just call the function with python train.py -resdec --train_model_path ...blabla

2023-04-11 17:51 UTC, Don-Yin reviewed
Thanks, I will merge this.

2023-04-12 09:38 UTC, ValerioB88 approved these changes

2023-04-13 16:10 UTC, merged